//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todoapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOREV
    {
        public int gorevId { get; set; }
        public string gorevAdi { get; set; }

        public string gorevTarihiString { get; set; }

        public Nullable<System.DateTime> gorevTarihi { get; set; }
        public Nullable<System.DateTime> animsat { get; set; }
        public Nullable<System.DateTime> yinele { get; set; }
        public Nullable<int> onemliId { get; set; }
        public Nullable<int> tamamlananId { get; set; }
        public Nullable<int> planlananId { get; set; }
        public Nullable<int> listeId { get; set; }
    
        public virtual LISTE LISTE { get; set; }
        public virtual ONEMLI ONEMLI { get; set; }
        public virtual PLANLANAN PLANLANAN { get; set; }
        public virtual TAMAMLANAN TAMAMLANAN { get; set; }
    }
}
