//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todoapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class todoEntities1 : DbContext
    {
        public todoEntities1()
            : base("name=todoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GOREV> GOREV { get; set; }
        public virtual DbSet<LISTE> LISTE { get; set; }
        public virtual DbSet<ONEMLI> ONEMLI { get; set; }
        public virtual DbSet<PLANLANAN> PLANLANAN { get; set; }
        public virtual DbSet<TAMAMLANAN> TAMAMLANAN { get; set; }
    }
}
